<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-GQ617UGP" failures="1" tests="7" name="Login Tests" time="59.51" errors="0" timestamp="2024-10-11T22:11:48 IST">
  <testcase classname="LoginTestTesting" name="TC_loginWithWrongPassword" time="6.782"/>
  <testcase classname="LoginTestTesting" name="TC_loginWithPasswordNull" time="5.124"/>
  <testcase classname="LoginTestTesting" name="TC_loginWithBothWrong" time="11.22"/>
  <testcase classname="LoginTestTesting" name="TC_loginWithEmailNull" time="10.993"/>
  <testcase classname="LoginTestTesting" name="TC_successfulLogin" time="21.982">
    <skipped/>
  </testcase> <!-- TC_successfulLogin -->
  <testcase classname="LoginTestTesting" name="TC_successfulLogin" time="16.374">
    <skipped/>
  </testcase> <!-- TC_successfulLogin -->
  <testcase classname="LoginTestTesting" name="TC_successfulLogin" time="13.484">
    <failure type="java.lang.AssertionError" message="Login was successful: https://srai.oyetest.com/login expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login was successful: https://srai.oyetest.com/login expected [true] but found [false]
at LoginTestTesting.TC_successfulLogin(LoginTestTesting.java:133)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- TC_successfulLogin -->
</testsuite> <!-- Login Tests -->
